name: Prod

on: 
  release:
    types: [published]

concurrency: prod

permissions:
  id-token: write  # for OIDC auth
  contents: write

jobs:

  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download build
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: build.zip

      - name: Unzip build
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip -d server/src

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Initialise terraform state
        working-directory: server/terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config "key=azure_experiment.prod.terraform.tfstate"

      - name: Apply terraform state
        working-directory: server/terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve -var="environment=prod"

      - name: Create environment tag
        uses: EndBug/latest-tag@v1.6.2
        with:
          ref: prod
