name: Stage

on:
  push:
    branches: [main]

concurrency: stage

env:
  DOTNET_VERSION: '8.0.x'

permissions:
  id-token: write  # for OIDC auth
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.build_version.outputs.build_version }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        working-directory: server/src
        run: |
          dotnet publish -c Release -o build 
      
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: server/src/build

      - name: Generate auto-incrementing ID
        id: build_number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: Generate build version
        working-directory: server/terraform
        id: build_version
        run: |
          BUILD_VERSION=1.0.${{steps.build_number.outputs.build_number}}
          echo "build_version=$BUILD_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create unique tag
        uses: EndBug/latest-tag@v1.6.2
        with:
          ref: ${{steps.build_version.outputs.build_version}}

  deploy:
    name: Deploy
    needs: [build]
    environment: stage
    outputs:
      function_name: ${{ steps.terraform_output.outputs.function_name }}
      function_url: ${{ steps.terraform_output.outputs.function_url }}
      resource_group_name: ${{ steps.terraform_output.outputs.resource_group_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: server/src/build

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Initialise terraform state
        working-directory: server/terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config "key=azure_experiment.stage.terraform.tfstate"

      - name: Apply terraform state
        working-directory: server/terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve -var="environment=stage"

      - name: Save output
        working-directory: server/terraform
        id: terraform_output
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          RESOURCE_GROUP_NAME=$(terraform output -raw azure_resource_group_name)
          FUNCTION_NAME=$(terraform output -raw azure_function_name)
          FUNCTION_URL=$(terraform output -raw azure_function_url)
          echo "resource_group_name=$RESOURCE_GROUP_NAME" >> "$GITHUB_OUTPUT"
          echo "function_name=$FUNCTION_NAME" >> "$GITHUB_OUTPUT"
          echo "function_url=$FUNCTION_URL" >> "$GITHUB_OUTPUT"

      - name: Create environment tag
        uses: EndBug/latest-tag@v1.6.2
        with:
          ref: stage

  test_api:
    name: Test API
    needs: [deploy]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build server api tests
        working-directory: server/test
        run: dotnet build

      # This is only necessary for browser testing
      # - name: Ensure browsers are installed
      #   working-directory: server/test
      #   run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Run server api tests
        working-directory: server/test
        env:
          AZURE_API_URL: ${{needs.deploy.outputs.function_url}}
        run: dotnet test

  create_release:
    name: Create Release
    needs: [build, test_api]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: server/src/build

      - name: Zip build
        working-directory: server/src
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build.zip
          draft: true
          tag: ${{needs.build.outputs.build_version}}
      
      # - name: Create release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
      #     asset_name: azblogfilter.linux-amd64.tar.gz
      #     asset_content_type: application/gzip
